server:
  port: 8081

order:
  host: http://localhost:8082

spring:
  datasource:
    platform: postgres
    driverClassName: org.postgresql.Driver
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5435/postgres}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:mysecretpassword}
  datasource-read:
    platform: postgres
    driverClassName: org.postgresql.Driver
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5435/postgres}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:mysecretpassword}
  minio:
    url: http:${MINIO_HOST://localhost}:${MINIO_PORT:9000}
    bucket: ${BUCKER_NAME:mybucket}
    access-key: ${ACCESS_KEY:user}
    storageAccountKey: ${STORAGE_ACCOUNT_KEY:password}
#    url: http:${MINIO_HOST://10.136.224.18}
#    bucket: ${BUCKER_NAME:mybucket}
#    access-key: ${ACCESS_KEY:ziJCYfekJ9iLMr0v2lIGL0vJUSwcGA0z}
#    storageAccountKey: ${STORAGE_ACCOUNT_KEY:IMLmdRMl_XE6WnR4CHDfWnw1aabguHvC}
  flyway:
    baseline-on-migrate: true
    enable: true
    location: classpath:/db/migration



